rice=read.csv("C:/Users/ankit/Downloads/wb_rice_production.csv",sep=",",head=T)
names(rice)
library(tseries)
adf.test(rice$W_Production)
acf(rice$W_Production)
library(urca)
kpss.test(rice$W_Production)
diff1=diff(rice$W_Production)
adf.test(diff1)
plot(rice$W_Production,type='l')
acf(diff1)
pacf(diff1)
diff2=diff(diff1)
acf(diff2)


jute=read.csv("C:/Users/ankit/Downloads/wb_jute_production.csv",sep=",",head=T)
names(jute)
adf.test(jute$weighted_mean_production)
acf(jute$weighted_mean_production)
diff2=diff(jute$weighted_mean_production)
plot(diff2,type='l')
adf.test(diff2)
diff3=diff(diff2)
adf.test(diff3)
pacf(jute$weighted_mean_production)
library(urca)
plot(diff3,type='l')

kpss.test(jute$weighted_mean_production)